### ISSUE TITLE
EPIC: Improvements on decidim-accountability module

### ISSUE THREAD

**Issue by josanFFiG** [AjuntamentdeBarcelona/decidim-barcelona#379]
# This is a Feature Proposal)

#### :tophat: Description

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

- As a participant I want to have a clear navigation and participant experience for the results of a participatory process, prioritizing the scopes instead of categories or subcategories. Sometimes the categories are less relevant than scopes.
- As a participant I want to see the projects list of a specific scope and the % of execution of a specific scope.
- As a participant I want to have further information of each project when I’m checking the timeline of the development of the project.
- As an administrator I want to add more information in the timeline of the development of the project

**Describe the solution you'd like:**
- [ ] As an administrator I want to add more visual information (image) to each scope.
- [ ] As a participant I want to navigate for the results selection navigation for scopes or for categories.
![Captura de 2021-11-18 16-31-30](https://user-images.githubusercontent.com/27766903/142457914-35069f85-7e79-44ec-a8ca-2a5bc3026124.png)
- [ ] The display for categories should  be mounted in three columns if there is no sub-categories (the present behavior is that the category card is just shown in the first left column in desktop version).
![Captura de 2021-11-18 16-31-46](https://user-images.githubusercontent.com/27766903/142457958-1c4eb00c-d58e-4f2c-874c-d13669512756.png)
- [ ] As a participant I want to see the list of projects (results) of a specific scope.
![Captura de 2021-11-18 16-32-08](https://user-images.githubusercontent.com/27766903/142457987-ee18013c-1a9d-4762-a31d-5642dc5a5ef5.png)
- [ ] As a participant I want to see the details of the timeline, title and description. Now there is just the description field.
![Captura de 2021-11-18 16-32-45](https://user-images.githubusercontent.com/27766903/142458161-22671d72-3bb4-4f99-a6d8-470c2fe03ef2.png)
- [ ] As an administrator i want to fill in the title and description field of the development of the project (result).
_Before:_
![Captura de 2021-11-02 13-48-09](https://user-images.githubusercontent.com/27766903/142460796-fc615aff-5300-4d90-9cac-5096228a870b.png)
![Captura de 2021-11-02 13-45-17](https://user-images.githubusercontent.com/27766903/142460813-f77ad118-7a87-4afd-9f60-0cc3f190a7f5.png)
![Captura de 2021-11-02 13-44-38](https://user-images.githubusercontent.com/27766903/142460839-61eecdc0-e6df-4ef6-9c39-a1862036a508.png)
![Captura de 2021-11-02 13-55-15](https://user-images.githubusercontent.com/27766903/142461047-7ae5f6e5-8124-4c8e-bbab-631951441835.png)
_After:_
![Captura de 2021-11-02 13-52-45](https://user-images.githubusercontent.com/27766903/142461084-3ae4a4bd-c7f8-452b-891f-ad65ad4fb573.png)
![Captura de 2021-11-02 13-58-58](https://user-images.githubusercontent.com/27766903/142461263-968b77de-9d84-4d85-a912-0e5dbff2e058.png)

**Describe alternatives you've considered**
Improve the cards for the navigation for scopes and above keep the same navigation by categories and subcategories, all in the same page.

**Additional context**
Decidim accountabilty gem: https://github.com/decidim/decidim/tree/develop/decidim-accountability 
 
**Does this issue could impact users' private data?** No

* ***Version***: 0.25
